[colors]
foreground = "#7b7b7b"
background = "#0e151f"
cursor_bg = "#7b7b7b"
cursor_border = "#7b7b7b"
cursor_fg = "#0e151f"
selection_bg = "#57606d"
selection_fg = "#0b1119"

ansi = ["#3d4551", "#de3b3d", "#6d8d22", "#9e7a21", "#2483d6", "#c841a4", "#279382", "#a09788"]
brights = ["#a09788", "#f56c66", "#8eaa57", "#b99956", "#5aa3eb", "#e16ebf", "#5eafa0", "#bfb5a6"]

[colors.tab_bar]
inactive_tab_edge = "#242c37"
background = "#19202b"

[colors.tab_bar.active_tab]
fg_color = "#0b1119"
bg_color = "#2483d6"

[colors.tab_bar.inactive_tab]
bg_color = "#19202b"
fg_color = "#57606d"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#19202b"
fg_color = "#2483d6"

[colors.tab_bar.new_tab_hover]
fg_color = "#0b1119"
bg_color = "#6d8d22"

[colors.tab_bar.new_tab]
fg_color = "#19202b"
bg_color = "#6d8d22"

[metadata]
aliases = []
author = "warthan07"
name = "Solarized OKLab"