# Solarized OKLab colors for Alacritty

[colors.primary]
background = "0x0e151f"
foreground = "0x797b7f"

[colors.normal]
black   = "0x424448"
red     = "0xde3b3d"
green   = "0x6d8d22"
yellow  = "0x9e7a21"
blue    = "0x2483d6"
magenta = "0xc841a4"
cyan    = "0x279382"
white   = "0x96989d"

[colors.bright]
black   = "0x96989d"
red     = "0xf56c66"
green   = "0x8eaa57"
yellow  = "0xb99956"
blue    = "0x5aa3eb"
magenta = "0xe16ebf"
cyan    = "0x5eafa0"
white   = "0xb4b7bb"

[colors]
indexed-colors = [
    { index = 16, color = "0xc06321" },
    { index = 17, color = "0xde3b3d" }]
  